control script

diff --git a/installers/etc/init.d/pidgeonsv b/installers/etc/init.d/pidgeonsv
--- a/installers/etc/init.d/pidgeonsv
+++ b/installers/etc/init.d/pidgeonsv
@@ -12,14 +12,24 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="Pidgeon irc services"
 NAME=pidgeonsv
-DAEMON="/usr/bin/pidgeon-sv"
+#DAEMON="/usr/bin/pidgeon-sv"
+DAEMON="/usr/bin/mono"
 PIDFILE=/var/run/$NAME.pid
 PIDFILEMONO="/var/run/$NAME"_MONO.pid
 SCRIPTNAME=/etc/init.d/$NAME
-DAEMON_ARGS="-p $PIDFILEMONO"
+FOLDER=/usr/share/pidgeonsv
+DAEMON_ARGS="pidgeon-sv.exe"
+#DAEMON_ARGS="-p $PIDFILEMONO"
+
+if [ ! -f "$FOLDER/pidgeon-sv.exe" ];then
+  echo "ERROR: you don't have the binary for daemon"
+  exit 1
+fi
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
+
+VERBOSE=yes
 
 # Define LSB log_* functions.
 # Depend on lsb-base (>= 3.2-14) to ensure that this file is present
@@ -35,9 +45,9 @@ do_start()
         #   0 if daemon has been started
         #   1 if daemon was already running
         #   2 if daemon could not be started
-        start-stop-daemon -b --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+        start-stop-daemon -d $FOLDER -b --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
                 || return 1
-        start-stop-daemon -b --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+        start-stop-daemon -d $FOLDER -b --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
                 $DAEMON_ARGS \
                 || return 2
         # Add code here, if necessary, that waits for the process to be ready
